### ISSUE TITLE
Auth failure with Nextcloud 13 & ejabberd

### ISSUE THREAD

**Issue by gibberfishinc** [jsxc/xmpp-cloud-auth#56]
I am using ejabberd 16.09 with the latest stable xmpp-cloud-auth and Nextcloud 13.0.3. In the past few days, when I try to log in to ejabberd via pidgin, I get the following error:

ejabberd     | 13:10:42.064 [error] extauth call '[<<"auth">>,<<"**********">>,<<"cloud.example.com">>,<<"***********">>]' didn't receive response
ejabberd     | 13:10:42.065 [info] ({socket_state,fast_tls,{tlssock,#Port<0.9473>,#Port<0.9474>},<0.597.0>}) Failed authentication for **********@cloud.example.com from ::FFFF:172.18.0.1

This same configuration worked fine before pulling the latest xmpp-cloud-auth code. I see that there was a recent migration to python 3, so I've installed the proper libraries. Have these recent changes been tested against Nextcloud and ejabberd specifically?

Any tips on where to start troubleshooting?

Thanks

**Comment by gibberfishinc** [comment]
xcauth.err complains:

> Traceback (most recent call last):
>   File "/opt/xmpp-cloud-auth/xcauth.py", line 14, in <module>
>     perform(args)
>   File "/opt/xmpp-cloud-auth/xclib/authops.py", line 103, in perform
>     xmpp.write_response(success)
>   File "/opt/xmpp-cloud-auth/xclib/ejabberd_io.py", line 29, in write_response
>     sys.stdout.write(token)
> TypeError: write() argument must be str, not bytes

**Comment by gibberfishinc** [comment]
> $ /opt/xmpp-cloud-auth/xcauth.py --auth-test ***** cloud.example.com **********

> 2018-06-08 13:40:06,519 DEBUG: Start external auth script 1.0.0+ for ejabberd with endpoint: https://cloud.example.com/apps/ojsxc/ajax/externalApi.php
> 2018-06-08 13:40:06,523 DEBUG: Token is too short: 11 != 23 (maybe not a token?)
> 2018-06-08 13:40:06,585 DEBUG: Starting new HTTPS connection (1): cloud.example.com
> 
> 2018-06-08 13:40:09,633 DEBUG: https://cloud.example.com:443 "POST /apps/ojsxc/ajax/externalApi.php HTTP/1.1" 200 43
> 2018-06-08 13:40:09,639 INFO: SUCCESS: Cloud says password for *****@cloud.example.com is valid
> True

**Comment by gibberfishinc** [comment]
xauth.log:
> 2018-06-08 14:02:42,949 DEBUG: Receive operation auth
> 2018-06-08 14:02:42,950 DEBUG: Token is too short: 11 != 23 (maybe not a token?)
> 2018-06-08 14:02:42,971 DEBUG: Starting new HTTPS connection (1): cloud.example.com
> 2018-06-08 14:02:46,374 DEBUG: https://cloud.example.com:443 "POST /apps/ojsxc/ajax/externalApi.php HTTP/1.1" 200 43
> 2018-06-08 14:02:46,380 INFO: SUCCESS: Cloud says password for *****@cloud.example.com is valid

So it looks like the issue isn't with Nextcloud but with ejabberd, right?

**Comment by gibberfishinc** [comment]
I rolled back to afbf801ef721514122a20ec179f8ae623762be82 and the python 2.x libs, and it works again, with no other config changes.

**Comment by chriscroome** [comment]
I also found that you have to use python2 and not 3, see [the comment I posted here](https://github.com/jsxc/xmpp-cloud-auth/issues/43#issuecomment-396319267), I tried your copy of the code with the [fix](https://github.com/gibberfishinc/xmpp-cloud-auth/commit/9e5856f49ba1fb98fd0d5ac34d75b5ca8f9a5e2a) but that generated this error:

```
/opt/xmpp-cloud-auth/xcauth.py -d -A admin example.org.uk XXX
2018-06-11 18:14:11,581 DEBUG: Start external auth script 1.0.0+ for ejabberd with endpoint: https://example.org.uk/apps/ojsxc/ajax/externalApi.php
2018-06-11 18:14:11,584 DEBUG: Token is too short: 12 != 23 (maybe not a token?)
Traceback (most recent call last):
  File "/opt/xmpp-cloud-auth/xcauth.py", line 14, in <module>
    perform(args)
  File "/opt/xmpp-cloud-auth/xclib/authops.py", line 68, in perform
    success = sc.auth()
  File "/opt/xmpp-cloud-auth/xclib/auth.py", line 116, in auth
    if self.auth_with_cache(unreach=False):
  File "/opt/xmpp-cloud-auth/xclib/auth.py", line 81, in auth_with_cache
    if key in self.ctx.cache_db:
  File "/usr/lib/python3.5/_collections_abc.py", line 603, in __contains__
    self[key]
  File "/usr/lib/python3/dist-packages/bsddb3/__init__.py", line 239, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python3/dist-packages/bsddb3/dbutils.py", line 67, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python3/dist-packages/bsddb3/__init__.py", line 239, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: Bytes or Integer object expected for key, str found
```
Does it work for you?

**Comment by gibberfishinc** [comment]
The latest commits to master include a conversion to python 3. Check the log.

**Comment by chriscroome** [comment]
I know, but [I get an error](https://github.com/jsxc/xmpp-cloud-auth/issues/43#issuecomment-396319267) unless I use python 2.

**Comment by gibberfishinc** [comment]
The sebang in xcauth.py specifically invokes python3, so that's what it will use even if you use python2 on the command line.

**Comment by chriscroome** [comment]
Thanks, I hadn't noticed that. The error I posted [above](https://github.com/jsxc/xmpp-cloud-auth/issues/56#issuecomment-396336726) was with python 3 and your [copy of the code](https://github.com/gibberfishinc/xmpp-cloud-auth):

```
python --version
Python 3.5.3
pwd
/opt/xmpp-cloud-auth
git describe
v1.0.0-27-g9e5856f
/opt/xmpp-cloud-auth/xcauth.py -d -A admin example.org.uk XXX
2018-06-11 18:45:09,564 DEBUG: Start external auth script 1.0.0+ for ejabberd with endpoint: https://example.org.uk/apps/ojsxc/ajax/externalApi.php
2018-06-11 18:45:09,567 DEBUG: Token is too short: 12 != 23 (maybe not a token?)
Traceback (most recent call last):
  File "/opt/xmpp-cloud-auth/xcauth.py", line 14, in <module>
    perform(args)
  File "/opt/xmpp-cloud-auth/xclib/authops.py", line 68, in perform
    success = sc.auth()
  File "/opt/xmpp-cloud-auth/xclib/auth.py", line 116, in auth
    if self.auth_with_cache(unreach=False):
  File "/opt/xmpp-cloud-auth/xclib/auth.py", line 81, in auth_with_cache
    if key in self.ctx.cache_db:
  File "/usr/lib/python3.5/_collections_abc.py", line 603, in __contains__
    self[key]
  File "/usr/lib/python3/dist-packages/bsddb3/__init__.py", line 239, in __getitem__
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
  File "/usr/lib/python3/dist-packages/bsddb3/dbutils.py", line 67, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/usr/lib/python3/dist-packages/bsddb3/__init__.py", line 239, in <lambda>
    return _DeadlockWrap(lambda: self.db[key])  # self.db[key]
TypeError: Bytes or Integer object expected for key, str found
```

Any idea what I'm doing wrong?

**Comment by gibberfishinc** [comment]
I haven't tested it with those exact arguments, but it works properly when invoked by ejabberd.

**Comment by chriscroome** [comment]
Thanks, I've switched to version afbf801 and python 2 as at least that way it works on the command line...

**Comment by MarcelWaldvogel** [comment]
I am sorry for any trouble you may have had. The move to Python 3 unfortunately has been a much more bumpy ride than I had imagined.

For stable builds, I recommend using [our 1.0 release](https://github.com/jsxc/xmpp-cloud-auth/releases/tag/v1.0.0).

@chriscroome: Can you try again whether b3cddd8 fixes your issue?

**Comment by poVoq** [comment]
Yeah, here too. 1.0 works like a charm on Ubuntu16.04 with ejabberd18.06 but I previously had a lot of strange issues I was not able to resolve with the dev-master.

**Comment by MarcelWaldvogel** [comment]
I haven't heard anything. Can you try again with [v1.1.0](https://github.com/jsxc/xmpp-cloud-auth/releases/tag/v1.1.0) or the newest from the master branch?

**Comment by MarcelWaldvogel** [comment]
Closing due to inactivity
