### ISSUE TITLE
when non-ascii based user cames with 'bad' ideas about securing their passwords..

### ISSUE THREAD

**Issue by NESC1US** [jsxc/xmpp-cloud-auth#60]
bellow is a result from xcauth.py --auth-test with made up password containing few central-european characters and its output

```
user@machine:~$ sudo -u ejabberd /opt/xmpp-cloud-auth/xcauth.py \
--auth-test 'nonasciiuser' 'example.com' 'ÜTýEfPássword'
2018-06-14 15:50:17,134 DEBUG: Start external auth script 1.0.0+ for ejabberd with endpoint: https://machine.example.com/index.php/apps/ojsxc/ajax/externalApi.php
2018-06-14 15:50:17,135 DEBUG: Could not decode token (maybe not a token?)
Traceback (most recent call last):
  File "/opt/xmpp-cloud-auth/xcauth.py", line 14, in <module>
    perform(args)
  File "/opt/xmpp-cloud-auth/xclib/authops.py", line 68, in perform
    success = sc.auth()
  File "/opt/xmpp-cloud-auth/xclib/auth.py", line 120, in auth
    r = self.auth_cloud()
  File "/opt/xmpp-cloud-auth/xclib/auth.py", line 51, in auth_cloud
    'password': self.password
  File "/opt/xmpp-cloud-auth/xclib/sigcloud.py", line 29, in cloud_request
    success, code, message, text = self.verbose_cloud_request(data)
  File "/opt/xmpp-cloud-auth/xclib/sigcloud.py", line 49, in verbose_cloud_request
    payload = utf8(urllib.parse.urlencode(data))
  File "/usr/lib/python3.5/urllib/parse.py", line 800, in urlencode
    v = quote_via(str(v), safe, encoding, errors)
  File "/usr/lib/python3.5/urllib/parse.py", line 723, in quote_plus
    return quote(string, safe, encoding, errors)
  File "/usr/lib/python3.5/urllib/parse.py", line 706, in quote
    string = string.encode(encoding, errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 0: surrogates not allowed
```

**Comment by NESC1US** [comment]
this is a mistake on my part, sorry. I cannot reproduce this behaviour from other machines.
