### ISSUE TITLE
sqlite3.OperationalError: table authcache already exists

### ISSUE THREAD

**Issue by Arnek1** [jsxc/xmpp-cloud-auth#66]
Hi,

as the title suggest I got an error when ejabberd invokes the xcauth script.
I actually I do not understand whats wrong in my setup.
ejabberd.err log reports:
```
18-08-05 16:02:30.813 [error] <0.62.0>@ejabberd_config:start:87 Failed to load configuration file /etc/ejabberd/ejabberd.yml
2018-08-05 16:02:30.813 [critical] <0.62.0>@ejabberd_app:start:69 Failed to start ejabberd application: invalid_option
2018-08-05 18:33:42.788 [error] <0.451.0>@extauth:handle_info:144 Failed to start external authentication program '/opt/xmpp-cloud-auth/xcauth.py'
2018-08-05 18:33:42.788 [error] <0.450.0> Supervisor 'extauth_pool_ANONYMIZEDSERVERNAME' had child 'extauth_pool_ANONYMIZEDSERVERNAME'_1' started with extauth:start_link('extauth_pool_ANONYMIZEDSERVERNAME'$
2018-08-05 18:33:42.801 [error] <0.452.0>@extauth:handle_info:144 Failed to start external authentication program '/opt/xmpp-cloud-auth/xcauth.py'
2018-08-05 18:33:42.802 [error] <0.450.0> Supervisor 'extauth_pool_ANONYMIZEDSERVERNAME'' had child 'extauth_pool_ANONYMIZEDSERVERNAME'_2' started with extauth:start_link('extauth_pool_ANONYMIZEDSERVERNAME'$
2018-08-05 18:33:42.828 [error] <0.460.0>@extauth:handle_info:144 Failed to start externalauthentication program '/opt/xmpp-cloud-auth/xcauth.py'
```
xcauth error log reports:
```
Traceback (most recent call last):
  File "/opt/xmpp-cloud-auth/xcauth.py", line 14, in <module>
    perform(args)
  File "/opt/xmpp-cloud-auth/xclib/authops.py", line 52, in perform
    bcrypt_rounds = args.cache_bcrypt_rounds)
  File "/opt/xmpp-cloud-auth/xclib/__init__.py", line 45, in __init__
    self.db = connection(Namespace(**h))
  File "/opt/xmpp-cloud-auth/xclib/db.py", line 61, in __init__
    self.db_create_cache(self.conn)
  File "/opt/xmpp-cloud-auth/xclib/db.py", line 105, in db_create_cache
    anyauth    TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')
sqlite3.OperationalError: table authcache already exists
```
xcaut.log reports many lines of:
```
INFO: Initializing /var/lib/xcauth/xcauth.sqlite3 from None, None, and None
```
I run Debian stretch, Nextcloud 13.0.5, ejabberd 18.06.
The ejabberd server is a fresh install and have actually only the admin user registered. 

I would be glad if I could get a hint how to resolve this issue. If any additional information is needed pleas let me know.

Thanks

Arne

**Comment by MarcelWaldvogel** [comment]
Could you send me the (anonymized) `xcauth.conf`?

A temporary workaround would be to tag/release v1.1.0

**Comment by Arnek1** [comment]
Here is the content of xcauth.conf:

# Example xcauth.py configuration file
#
# Preferably put this in /etc,
# and make it readable only for the user the XMPP server is running under
#
# Config files are only supported if ConfigArgParse python module
# is installed. Install e.g. using "pip install ConfigArgParse".
# If "xcauth.py -h" shows the "-c" option, it is installed.

# Type: ejabberd or prosody
#
type=ejabberd

# URL: Where JSXC for Nextcloud (>=3.2.0) can be queried
# Shown in the Nextcloud JSXC administration settings
#
url=https://ANONYMIZEDSERVERNAME/index.php/apps/ojsxc/ajax/externalApi.php

# Secret: Secure API token
# Shown in the Nextcloud JSXC administration settings
# :warning: Should not fall into the wrong hands!
#
#secret=0123456789ABCDEF
secret=SECTRET-TOKEN-FROM-NEXTCLOUD

# Log: Log directory
# In this directory, extauth.{log,err} will be created
#
log=/var/log/xcauth

# Debug: Log more
#
#debug


I will try to out V1.1.0 in the next few days

**Comment by MarcelWaldvogel** [comment]
> I will try to out V1.1.0 in the next few days

By then, the bug should be fixed. ;-)

**Comment by MarcelWaldvogel** [comment]
Which version are you running?

Did you run a previous version of `xcauth` once?

**Comment by MarcelWaldvogel** [comment]
Based on your problem, I realized that starting multiple processes at once (which recent *ejabberd*s can do) would cause similar errors (but not persistently).

The current commit works around this and should also allow your xcauth to start.

Could you please test it?

**Comment by Arnek1** [comment]
I run version 1.2.0
The xcauth.conf file I send was not made from the template included in the git download but was based on the instruction from Raspi HowTo. It seems a bit outdated compared to the git version.

Nevertheless I will try the new commit.

**Comment by Arnek1** [comment]
With the new commit the logs showing no errors any more.
From a first impression it seems to work.

Thanks!

**Comment by MarcelWaldvogel** [comment]
Regarding `xcauth.conf` sample: It is nice and short (and OK for most purposes). I have added a comment in the wiki, however.
