### ISSUE TITLE
can't auth new users

### ISSUE THREAD

**Issue by wargreen** [jsxc/xmpp-cloud-auth#7]
All work well with my user, but with a new test user :

ejabberd.log
```
2017-04-06 15:35:37.845 [error] <0.580.0>@extauth:loop:130 extauth call '[<<"auth">>,<<"test1">>,<<"localhost">>,<<"*********">>]' didn't receive response
2017-04-06 15:35:37.846 [info] <0.579.0>@ejabberd_c2s:wait_for_feature_request:757 ({socket_state,ejabberd_http_bind,{http_bind,<0.578.0>,{{0,0,0,0,0,0,0,1},53071}},ejabberd_http_bind}) Failed authentication for test1@localhost from IP ::1
2017-04-06 15:35:55.923 [info] <0.578.0>@ejabberd_http_bind:handle_info:519 Session timeout. Closing the HTTP bind session: <<"41aed1083f062fa504764bc7c8b07ef9372b6212">>
```

extauth.err
```
TraceTraceback (most recent call last):
  File "/opt/xmpp-cloud-auth/external_cloud.py", line 176, in <module>
    success = auth(data[1], data[2], data[3])
  File "/opt/xmpp-cloud-auth/external_cloud.py", line 113, in auth
    if verify_token(username, server, password):
  File "/opt/xmpp-cloud-auth/external_cloud.py", line 23, in verify_token
    token = b64decode(password.translate(usersafe_encoding) + "=======")
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect paddingback (most recent call last):
  File "/opt/xmpp-cloud-auth/external_cloud.py", line 176, in <module>
    success = auth(data[1], data[2], data[3])
  File "/opt/xmpp-cloud-auth/external_cloud.py", line 113, in auth
    if verify_token(username, server, password):
  File "/opt/xmpp-cloud-auth/external_cloud.py", line 23, in verify_token
    token = b64decode(password.translate(usersafe_encoding) + "=======")
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
```

**Comment by sualko** [comment]
Please test https://github.com/jsxc/xmpp-cloud-auth/issues/6#issuecomment-292150306

**Comment by wargreen** [comment]
yes, login to nextcloud and ejabberd work with this.
